# Generated by Django 4.0 on 2021-12-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product_alter_customer_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statis',
            new_name='status',
        ),
    ]
